name: Hourly Team Notification

on:
  schedule:
    - cron: '0 * * * *'  # Executes every hour

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Team
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: 'Hey, chalg`imasdan, proyektingni qil!!! Orqada qolyapsan axir!!!'
